all:
  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/jrenewhite/.ssh/id_ed25519_jrenewhite
    ssh_admin_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAT+GcYGv/IRDu6Lh2ZaPTZbMoTraNq1Sz1blFQ4dXev jrenewhite@hotmail.com"
  children:
    core:
      hosts:
        peru-management:
          ansible_host: 192.168.10.10
          desired_ip: 192.168.10.10
          role_profile: core
        peru-nas:
          ansible_host: 192.168.10.11
          desired_ip: 192.168.10.11
          role_profile: nas
          ansible_user: root
          ansible_become: false
    services:
      hosts:
        peru-services:
          ansible_host: 192.168.10.12
          desired_ip: 192.168.10.12
          role_profile: services
    gpu:
      hosts:
        peru-ai-gpu:
          ansible_host: 192.168.10.13
          desired_ip: 192.168.10.13
          role_profile: gpu
    arm:
      hosts:
        peru-rpi5-ultra:
          ansible_host: 192.168.10.14
          desired_ip: 192.168.10.14
          role_profile: arm
        peru-rpi5-max:
          ansible_host: 192.168.10.15
          desired_ip: 192.168.10.15
          role_profile: arm
        peru-rpi5-a:
          ansible_host: 192.168.10.16
          desired_ip: 192.168.10.16
          role_profile: arm
        peru-rpi4-a:
          ansible_host: 192.168.10.17
          desired_ip: 192.168.10.17
          role_profile: arm
        peru-rpi4-b:
          ansible_host: 192.168.10.18
          desired_ip: 192.168.10.18
          role_profile: arm
