nfs_app_identities:
  - name: apps
    uid: 3000
    gid: 3000
  - name: jrenewhite
    groups:
      - media_rw
      - docs_rw

pihole_enabled: true
pihole_role: primary
pihole_listen_ip: 192.168.0.10
pihole_web_port: 8200
pihole_stack_dir: /opt/stacks/pihole-primary

router_dns_secret_file: /opt/colibri-secrets/router.env
router_dns_helper_path: /opt/colibri/bin/router-cli.expect
router_dns_cutover_script: /opt/colibri/bin/router-dns-cutover-with-rollback.sh
router_dns_log_dir: /var/log/colibri
router_dns_canary_host: 192.168.0.14
router_dns_canary_backup_host: 192.168.0.15
