all:
  vars:
    ansible_user: jrenewhite
    ansible_become: true
    ansible_ssh_private_key_file: /home/jrenewhite/.ssh/id_ed25519_jrenewhite
    ssh_admin_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAT+GcYGv/IRDu6Lh2ZaPTZbMoTraNq1Sz1blFQ4dXev jrenewhite@hotmail.com"
  children:
    core:
      hosts:
        management:
          ansible_host: 192.168.0.172
          desired_ip: 192.168.0.10
          role_profile: core
        nas:
          ansible_host: 192.168.0.190
          ansible_user: root
          ansible_become: false
          desired_ip: 192.168.0.11
          role_profile: nas
    services:
      hosts:
        services:
          ansible_host: 192.168.0.185
          desired_ip: 192.168.0.12
          role_profile: services
    gpu:
      hosts:
        ai-gpu:
          ansible_host: 192.168.0.186
          desired_ip: 192.168.0.13
          role_profile: gpu
    arm:
      hosts:
        orangepi5-ultra:
          ansible_host: 192.168.0.178
          desired_ip: 192.168.0.14
          role_profile: arm
        orangepi5-max:
          ansible_host: 192.168.0.181
          desired_ip: 192.168.0.15
          role_profile: arm
        orangepi5-a:
          ansible_host: 192.168.0.187
          desired_ip: 192.168.0.16
          role_profile: arm
        orangepi5-b:
          ansible_host: 192.168.0.193
          desired_ip: 192.168.0.17
          role_profile: arm
